# Generated by Django 4.0.6 on 2022-09-01 19:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_card_loan_notification_receipt_reward_thirdparty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, null=True)),
                ('symbol', models.CharField(max_length=5, null=True)),
                ('amount', models.BigIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='account_balance',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='number',
            new_name='card_number',
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Account_wallet', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Card_account', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='card',
            name='issuer',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='security_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Card_wallet', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='loan',
            name='guaranter',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Loan_wallet', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thirdparty_account', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='date_of_issue',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='issuer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thirdparty_wallet', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='destination_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_destination', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='message',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='origin_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_origin', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_receipt', to='wallet.receipt'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='transaction_charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='transaction_description',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='transaction_type',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='gender',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='transaction',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='name',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer_ID',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Thirdparty_currency', to='wallet.currency'),
        ),
    ]
