# Generated by Django 4.0.6 on 2022-10-04 16:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_currency_rename_balance_account_account_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_balance',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='security_code',
            new_name='CVV_Security_code',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_number',
            new_name='cardholder_number',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='date_of_issue',
            new_name='date_issued',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='points',
            new_name='bonus_points',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Date_time',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='guaranter',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='name',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='date_of_issue',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='thirdparty',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_ID',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='destination_account',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='message',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='origin_account',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_charge',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_description',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='wallet',
        ),
        migrations.AddField(
            model_name='account',
            name='account_pin',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='cardholder_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_picture'),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_term',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='pay_due_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.thirdparty'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='date_of_reward',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_a', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_b', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_c', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_ref',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_wallet', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_wallet', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('K', 'Shilling'), ('$', 'Dollar'), ('EU', 'Euros')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('w', 'withdraw'), ('S', 'Savings'), ('D', 'Deposit')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('C', 'Credit card'), ('D', 'Debit card')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='card',
            name='issuer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcation_b', to='wallet.transaction'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='gender',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.transaction'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='account',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='transaction_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
